trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'OwaspVariableGroup'

steps:
  - task: CmdLine@2
    displayName: 'Checkout branch'
    inputs:
      script: |
        git config --global user.email "AxiansIS@vinci-energies.net"
        git config --global user.name "AxiansIS"
        git checkout -b $(Build.SourceBranchName)

  - task: MavenAuthenticate@0
    displayName: 'Maven Authenticate'
    inputs:
      mavenServiceConnections: 'github-axians-oss'

  - task: Bash@3
    displayName: 'Add Maven Central to settings.xml'
    inputs:
      targetType: 'inline'
      script: |
        cat <<EOF > ~/.m2/settings.xml
        <settings>
            <servers>
                <server>
                    <id>central</id>
                    <username>${SonatypeUsername}</username>
                    <password>${SonatypePassword}</password>
                </server>
            <servers>
        </settings>
        EOF      

  - task: Maven@4
    displayName: 'Maven prepare'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m -s ~/.m2/settings.xml -Dusername=PAT -Dpassword=$(System.AccessToken)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'release:prepare'
      options: '-B -DscmCommentPrefix="[skip ci]"'

  - task: Maven@4
    displayName: 'Maven release'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m -s ~/.m2/settings.xml -Dusername=PAT -Dpassword=$(System.AccessToken) --enable-native-access=ALL-UNNAMED -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false -Dowasp.db.connectionString=$(OwaspDbConnectionString) -Dowasp.db.username=$(OwaspDbUsername) -Dowasp.db.password=$(OwaspDbPassword) -Dowasp.nvd.api_key=$(OwaspNvdApiKey)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'release:perform -P sharedcare-release'
      options: '-B -DscmCommentPrefix="[skip ci]"'

  - task: SonarCloudPrepare@3
    displayName: 'Prepare Analysis on SonarCloud'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'axians'
      scannerMode: 'cli'
      configMode: manual
      cliProjectKey: nl.axians:axians
      cliProjectName: Axians Super POM
      cliSources: src
      extraProperties: |
        sonar.projectBaseDir=./target/checkout
        sonar.java.binaries=target/classes
        sonar.java.libraries=**/*
        sonar.sources=.
        sonar.coverage.exclusions=src/test/**
        sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        sonar.junit.reportPaths=target/surefire-reports
        sonar.externalIssuesReportPaths=target/sonar-dependency-check-report.json

  - task: SonarCloudAnalyze@3
    displayName: 'Perform Sonar scan'

  - task: SonarCloudPublish@3
    displayName: 'Publish analysis to SonarCloud'
    inputs:
      pollingTimeoutSec: '300'

