trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'OwaspVariableGroup'

steps:
  - script: |
      echo $(OwaspDbConnectionString)
      echo $(OwaspDbPassword)
      echo $(OwaspDbUsername)
      echo $(OwaspNvdApiKey)
    displayName: 'Display variables'

