trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'OwaspVariableGroup'

steps:
  - script: |
      echo $(OwaspDbConnectionString)
      echo $(OwaspDbPassword)
      echo $(OwaspDbUsername)
      echo $(OwaspNvdApiKey)
    displayName: 'Display variables'

  - task: Maven@4
    displayName: 'Maven package'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: >
        -Xmx3072m
        -Dowasp.db.connectionString=$(OwaspDbConnectionString) 
        -Dowasp.db.username=$(OwaspDbUsername) 
        -Dowasp.db.password=$(OwaspDbPassword) 
        -Dowasp.nvd.api_key=$(OwaspNvdApiKey)
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean verify -P qa'
      options: >
        -B -DscmCommentPrefix="[skip ci]" 
        -X